/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Heading: typeof import('./src/components/heading.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Item1: typeof import('./src/components/elements/heading/item-1.vue')['default']
    Itme1: typeof import('./src/components/elements/heading/itme1.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
